
before_all do
  Dotenv.load ".env.secrets"
end

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :run_tests do
    run_tests(scheme: "Authenticator")
  end
  
  desc "Sync signing"
  lane :signing do
    app_store_connect_api_key(
      is_key_content_base64: "true"
    )  
    match
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app
  end

  desc "Release"
  lane :release do
    increment_build_number
    build
    upload_to_testflight
  end

end